# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c726502db12c4f20c7d096a24f9516d01613654544e4f57ba0ba8ea325308e53a816e1cfd801b5c936f37d5f922d0899521f4dc64c8aff51cc0397247f1b13f0

test:
  secret_key_base: 9d0dbb2f95b81c305d763a19fbb196004dd357a9b74cbb84d9901086b93df77ba08ba608d756e7a8deb9cfcafd35128ca05b68952b1ed855c26a3a8265807127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
